trigger:
  branches:
    include:
      - main
      - develop

pool:
  name: Agents On-Premise
  demands:
    - Agent.Name -equals agent-build-1

resources:
  repositories:
    - repository: templates
      type: git
      name: Vetta/platform-vetta-automation
      ref: master

steps:
  - template: tasks/docker-build-and-push.yml@templates
    parameters:
      imageName: digital-grafana-base
      imageTags: "11.5.0-pre,latest"
      containerRegistry: "vettadigitalcontainers-Platform"
