trigger:
  branches:
    include:
      - main
      - develop

pool:
  name: Agents On-Premise

variables:
  dockerImageName: "digital-grafana"
  dockerImageTag: "latest"

steps:
  # Docker task roughly matching script at packaging/docker/build.sh
  - task: Docker@2
    displayName: Build Docker Image
    inputs:
      command: "build"
      arguments: |
        --no-cache=true
        --build-arg BINGO=false
        -t $(dockerImageName):$(dockerImageTag)"
      dockerfile: "$(Build.SourcesDirectory)/Dockerfile"
      buildContext: "$(Build.SourcesDirectory)"
    env:
      DOCKER_BUILDKIT: "1"
